trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: "22"

  - script: npm ci
    workingDirectory: frontend
    displayName: "Install frontend dependencies"

  - script: npm ci
    workingDirectory: backend
    displayName: "Install backend dependencies"

  - script: npm run build
    workingDirectory: frontend
    displayName: "Build frontend"
    env:
      VITE_CLARITY_PROJECT_ID: $(VITE_CLARITY_PROJECT_ID)
      VITE_DEMO_VIDEO_URL: $(VITE_DEMO_VIDEO_URL)

  - script: | 
      mkdir -p backend/public
      cp -r frontend/dist/. backend/public/
    displayName: "Move frontend build to backend public folder"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "backend"
      ArtifactName: "drop"
    displayName: "Publish backend artifact"